Работа с клиентом
1 Выберите дом клиенту. Клиент хочет дом с видом на набережную(waterfront), как минимум с тремя ванными и с подвалом.
- Сколько вариантов есть у клиента?

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('kc_house_data.csv', sep=',')

In [12]:
df[(df['waterfront'] == 1) & (df['bathrooms'] >= 3) & (df['sqft_basement'] != 0)].shape[0]

41

- Выведите все варианты таблицей

In [13]:
df[(df['waterfront'] == 1) & (df['bathrooms'] >= 3) & (df['sqft_basement'] != 0)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
300,3225069065,20140624T000000,3075000.0,4,5.00,4550,18641,1.0,1,4,...,10,2600,1950,2002,0,98074,47.6053,-122.077,4550,19508
457,2122039094,20141126T000000,705000.0,3,3.00,1970,20978,2.0,1,3,...,9,1770,200,1980,0,98070,47.3844,-122.438,2280,75396
1164,1247600105,20141020T000000,5110800.0,5,5.25,8010,45517,2.0,1,4,...,12,5990,2020,1999,0,98033,47.6767,-122.211,3430,26788
1261,7636800041,20140625T000000,995000.0,3,4.50,4380,47044,2.0,1,3,...,9,3720,660,1968,1990,98166,47.4734,-122.365,2460,18512
1315,7558700030,20150413T000000,5300000.0,6,6.00,7390,24829,2.0,1,4,...,12,5000,2390,1991,0,98040,47.5631,-122.210,4320,24619
1361,1925069082,20150511T000000,2200000.0,5,4.25,4640,22703,2.0,1,4,...,8,2860,1780,1952,0,98052,47.6393,-122.097,3140,14200
2626,7738500731,20140815T000000,4500000.0,5,5.50,6640,40014,2.0,1,4,...,12,6350,290,2004,0,98155,47.7493,-122.280,3030,23408
2864,4114601570,20141118T000000,3600000.0,3,3.25,5020,12431,2.0,1,4,...,10,3420,1600,1941,2002,98144,47.5925,-122.287,3680,12620
3914,9808700762,20140611T000000,7062500.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
3934,1269200229,20140723T000000,1379900.0,3,3.25,3786,38038,1.0,1,4,...,9,1934,1852,1978,2006,98070,47.3907,-122.448,2850,33361
5760,623059016,20140717T000000,1100000.0,4,3.25,3190,11774,2.0,1,4,...,8,2610,580,1956,1991,98178,47.5033,-122.225,2240,8725
6233,2024069008,20140619T000000,2200000.0,5,4.75,5990,10450,2.0,1,4,...,11,4050,1940,2002,0,98027,47.5554,-122.077,3330,14810
6508,4217402115,20150421T000000,3650000.0,6,4.75,5480,19401,1.5,1,4,...,11,3910,1570,1936,0,98105,47.6515,-122.277,3510,15810
7989,9362000040,20140623T000000,3400000.0,3,4.50,5230,17826,2.0,1,4,...,10,3740,1490,2005,0,98040,47.5348,-122.243,3670,17826
8092,1924059029,20140617T000000,4668000.0,5,6.75,9640,13068,1.0,1,4,...,12,4820,4820,1983,2009,98040,47.5570,-122.210,3270,10454
8163,1724069079,20150319T000000,1452000.0,2,3.25,2070,3128,2.0,1,3,...,9,1760,310,1988,0,98075,47.5686,-122.060,2740,3568
8784,3343302110,20150306T000000,1800000.0,3,3.00,2790,13295,2.0,1,4,...,10,2370,420,1933,1989,98006,47.5466,-122.197,3140,11949
10263,625059036,20140813T000000,2700000.0,5,4.00,4230,27295,2.0,1,4,...,8,3230,1000,1949,1985,98033,47.6803,-122.214,2660,27295
11257,3761100045,20140618T000000,3000000.0,4,4.25,4850,12445,2.0,1,4,...,10,3850,1000,1989,0,98034,47.7011,-122.244,3350,12210
11402,3426049284,20140819T000000,2300000.0,4,3.25,4110,15929,2.0,1,4,...,12,2720,1390,2001,0,98115,47.6934,-122.271,2640,15929
11424,5119400075,20140620T000000,950000.0,3,3.25,3050,18892,1.0,1,4,...,8,1650,1400,1962,0,98198,47.3881,-122.326,1170,70973
11446,624069035,20141209T000000,2750000.0,4,4.00,4130,5575,2.0,1,4,...,10,2860,1270,1993,0,98075,47.5968,-122.083,2980,5575
11844,2623039082,20150218T000000,770000.0,3,3.50,2050,21744,2.0,1,4,...,9,1750,300,1930,0,98166,47.4536,-122.376,2300,12200
12459,4114601580,20140724T000000,1900000.0,6,4.00,3020,13237,2.0,1,4,...,8,2840,180,1942,1983,98144,47.5924,-122.287,3680,12620
12935,3222049044,20140612T000000,835000.0,3,3.00,2790,12523,2.0,1,4,...,8,1600,1190,1977,0,98198,47.3571,-122.324,2990,11476
13710,2923500230,20141216T000000,2600000.0,4,4.50,5270,12195,2.0,1,4,...,11,3400,1870,1979,0,98027,47.5696,-122.090,3390,9905
13967,3126059023,20150303T000000,3395000.0,4,3.50,4730,47870,1.0,1,4,...,10,2940,1790,1954,0,98033,47.6967,-122.216,3250,49346
14083,3625059043,20140904T000000,3300000.0,5,4.75,6200,13873,2.0,1,4,...,11,4440,1760,1989,0,98008,47.6050,-122.112,2940,13525
14619,7936500109,20140725T000000,2230000.0,3,3.00,3620,28064,2.0,1,4,...,10,2370,1250,1977,0,98136,47.5516,-122.398,2550,34713
14822,3623500408,20150330T000000,2600000.0,3,3.00,3410,16015,2.0,1,4,...,10,2220,1190,1973,0,98040,47.5721,-122.239,3760,16572
15482,624069108,20140812T000000,3200000.0,4,3.25,7000,28206,1.0,1,4,...,12,3500,3500,1991,0,98075,47.5928,-122.086,4913,14663
15668,4030100290,20141001T000000,1680000.0,5,3.50,5170,7197,3.0,1,4,...,11,3520,1650,1998,0,98155,47.7561,-122.271,3020,12880
16817,825059178,20140923T000000,2574000.0,4,3.75,4475,20424,2.0,1,4,...,12,2659,1816,1999,0,98033,47.6646,-122.208,4340,5250
17767,7352200450,20150115T000000,2050000.0,4,3.25,3580,19989,1.5,1,4,...,7,3480,100,1915,1965,98125,47.7087,-122.276,2410,6389
18199,3625059152,20141230T000000,3300000.0,3,3.25,4220,41300,1.0,1,4,...,11,2460,1760,1958,1987,98008,47.6083,-122.110,3810,30401
18455,8043700300,20140608T000000,2700000.0,4,3.25,4420,7850,2.0,1,4,...,11,3150,1270,2001,0,98008,47.5720,-122.102,2760,8525
18556,6613000930,20140902T000000,2950000.0,4,3.25,3890,25470,2.0,1,3,...,10,3030,860,1923,0,98105,47.6608,-122.269,4140,19281
20325,518500480,20140811T000000,3000000.0,3,3.50,4410,10756,2.0,1,4,...,11,3430,980,2014,0,98056,47.5283,-122.205,3550,5634
20767,8043700105,20150417T000000,2300000.0,4,4.00,4360,8175,2.5,1,4,...,10,3940,420,2007,0,98008,47.5724,-122.104,2670,8525
21201,518500460,20141008T000000,2230000.0,3,3.50,3760,5634,2.0,1,4,...,11,2830,930,2014,0,98056,47.5285,-122.205,3560,5762
21576,9253900271,20150107T000000,3567000.0,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270

2 Выберите дом клиенту.
Клиент хочет дом
- либо с очень красивым видом(параметр 'view' - больше 3) из окна, либо с видом на набережную(waterfront)
- и в очень хорошем состоянии(condition > 4) и год постройки не меньше 1980 года.
- В какой ценовом диапазоне будут дома?

In [14]:
df[(df['view'] >3) | (df['waterfront'] == 1) & (df['condition'] > 4) & (df['yr_built'] > 1980)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21,2524049179,20140826T000000,2000000.0,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
58,7922800400,20140827T000000,951000.0,5,3.25,3250,14342,2.0,0,4,...,8,3250,0,1968,0,98008,47.5880,-122.116,2960,11044
230,8096000060,20150413T000000,655000.0,2,1.75,1450,15798,2.0,1,4,...,7,1230,220,1915,1978,98166,47.4497,-122.375,2030,13193
246,2025069065,20140929T000000,2400000.0,4,2.50,3650,8354,1.0,1,4,...,9,1830,1820,2000,0,98074,47.6338,-122.072,3120,18841
264,2123039032,20141027T000000,369900.0,1,0.75,760,10079,1.0,1,4,...,5,760,0,1936,0,98070,47.4683,-122.438,1230,14267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20767,8043700105,20150417T000000,2300000.0,4,4.00,4360,8175,2.5,1,4,...,10,3940,420,2007,0,98008,47.5724,-122.104,2670,8525
20923,7852070210,20140527T000000,1149000.0,4,3.00,5940,11533,2.0,0,4,...,11,4950,990,2004,0,98065,47.5443,-121.870,4240,12813
21050,2424059170,20150219T000000,900000.0,5,6.00,7120,40806,2.0,0,4,...,12,5480,1640,2007,0,98006,47.5451,-122.114,3440,36859
21201,518500460,20141008T000000,2230000.0,3,3.50,3760,5634,2.0,1,4,...,11,2830,930,2014,0,98056,47.5285,-122.205,3560,5762
21576,9253900271,20150107T000000,3567000.0,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270

In [15]:
df[(df['view'] >3) | (df['waterfront'] == 1) & (df['condition'] > 4) & (df['yr_built'] > 1980)].describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,3.190000e+02,3.190000e+02,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.0,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000
mean,4.991007e+09,1.463711e+06,3.633229,2.793887,3351.473354,21594.987461,1.605016,0.423197,4.0,3.567398,9.078370,2516.529781,834.943574,1966.150470,349.623824,98095.752351,47.575866,-122.263708,2843.752351,18867.141066
std,2.931542e+09,9.522096e+05,1.107561,1.079593,1553.260668,35742.685384,0.580696,0.494842,0.0,0.744584,1.604868,1242.594566,768.668466,27.219165,758.888162,61.667332,0.112742,0.131633,775.314206,27496.960486
min,9.800107e+07,2.520000e+05,1.000000,0.750000,680.000000,1171.000000,1.000000,0.000000,4.0,1.000000,5.000000,680.000000,0.000000,1903.000000,0.000000,98001.000000,47.249800,-122.511000,1010.000000,1505.000000
25%,2.608125e+09,8.175000e+05,3.000000,2.250000,2425.000000,8421.000000,1.000000,0.000000,4.0,3.000000,8.000000,1680.000000,0.000000,1948.000000,0.000000,98036.000000,47.513300,-122.376000,2385.000000,8311.500000
50%,4.114602e+09,1.185000e+06,4.000000,2.500000,3050.000000,13122.000000,1.500000,0.000000,4.0,3.000000,9.000000,2180.000000,810.000000,1968.000000,0.000000,98115.000000,47.578400,-122.276000,2810.000000,12528.000000
75%,7.855100e+09,1.850000e+06,4.000000,3.250000,3911.000000,20712.000000,2.000000,1.000000,4.0,4.000000,10.000000,2940.000000,1375.000000,1989.000000,0.000000,98146.000000,47.659800,-122.194000,3290.000000,19014.500000
max,9.829200e+09,6.885000e+06,7.000000,8.000000,13540.000000,322188.000000,3.000000,1.000000,4.0,5.000000,13.000000,9410.000000,4820.000000,2014.000000,2015.000000,98198.000000,47.775700,-121.739000,5380.000000,248292.000000

In [16]:
df[(df['view'] >3) | (df['waterfront'] == 1) & (df['condition'] > 4) & (df['yr_built'] > 1980)]['price'].min()

252000.0

In [17]:
df[(df['view'] >3) | (df['waterfront'] == 1) & (df['condition'] > 4) & (df['yr_built'] > 1980)]['price'].max()

6885000.0

3 Выберите дом клиенту. Клиент хочет дом
- без подвала
- с двумя этажами
- стоимостью до 150000.
- Какая оценка по состоянию у таких домов в среднем?

In [19]:
df[(df['sqft_basement'] == 0) & (df['floors'] == 2) & (df['price'] < 150000)]['condition'].mean()

2.8333333333333335